config/routes.rb
Rails.application.routes.draw do
  root 'calculator#index'
  post '/', to: 'calculator#index'

  get "stats", to: "calculator#stats"
  post 'stats', to: 'calculator#calculate_stats'
  get "polynomial", to: "calculator#polynomial"
  get "linear", to: "calculator#linear"
  post 'linear', to: 'calculator#calculate_linear'
  get 'quadratic', to: 'calculator#quadratic'
  post 'quadratic', to: 'calculator#calculate_quadratic'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Calculator App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="sidebar">
      <h2>Omni-Calculator</h2>
      <nav>
        <ul>
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Calculator', root_path, data: { turbo: false } %></li>
          <li class="<%= 'active' if current_page?(polynomial_path) %>"><%= link_to 'Polynomials', polynomial_path, data: { turbo: false } %></li>
          <li class="<%= 'active' if current_page?(stats_path) %>"><%= link_to 'Statistics', stats_path, data: { turbo: false } %></li>
          <li class="<%= 'active' if current_page?(linear_path) %>"><%= link_to 'Linear Equations', linear_path, data: { turbo: false } %></li>
          <li class="<%= 'active' if current_page?(quadratic_path) %>"><%= link_to 'Quadratic Equations', quadratic_path, data: { turbo: false } %></li>
        </ul>
      </nav>
    </div>
    <div id="main-content">
      <%= yield %>
    </div>
    <%= stylesheet_link_tag 'sidebar', media: 'all' %>
  </body>
</html>